<?php
    /**
     * @var Admin\Entity\Article[] $articles;
     * @var Admin\Entity\Article $article;
     */
?>

<h2>Articles list</h2>
<a href="<?php echo $this->url('admin/default', array('controller' => 'article', 'action' => 'add')) ?>">Add new article</a>

<br/><br/>
<ul>
    <?php foreach($articles as $article): ?>
        <li>
            <?php echo $article->id .' - ' .$article->text .' | '; ?>
            <a href="<?php echo $this->url('admin/default', array('controller' => 'article', 'action' => 'edit', 'id' => $article->id)) ?>">Edit</a> |
            <a href="javascript:void(0)" class="check-link delete" data-toggle="modal" data-target="#myModal" data-id="<?php echo $article->id ?>" data-value="<?php echo $article->text; ?>">
                Delete
            </a>
        </li>
    <?php endforeach; ?>
</ul>

<?php echo $this->partial('admin/blocks/modal_window.phtml', array(
    'title_value'=> 'Delete article',
    'body_value' => 'Delete article ',
    'cancel_value' => 'Cancel',
    'confirm_value' => 'Delete',
    'table_name' => 'article',
)); ?>