<?php
    /**
     * @var \Admin\Entity\Entity[] $entities;
     * @var \Admin\Entity\Entity $entity;
     * @var string $current_entity_name;
     */
?>

<div class="list-group">
    <?php foreach($entities as $entity): ?>
        <a href="<?php echo $this->url('admin/default', array(
            'controller' => 'crud',
            'table' => $entity->name,
        )); ?>" class="list-group-item<?php echo (isset($current_entity_name) && $current_entity_name == $entity->name) ? ' active' : ''; ?>">
            <?php echo ucfirst($entity->pluralName); ?>
        </a>
    <?php endforeach; ?>
</div>