<!--<ul class="articles-list">
    <?php /*foreach($articles as $article): */?>
        <?php /*echo $article->getId() .' - ' .$article->getText() .'<br/>'; */?>
    <?php /*endforeach; */?>
</ul>-->

<?php /*echo $this->url('admin/article'); */?><!--
<br/>-->
<?php /*echo $this->url('admin/article/add'); */?><!--
<br/>-->

<a href="<?php echo $this->url('admin/default', array('controller' => 'article')); ?>">Articles</a>